/* Lost Ruby - Earth II production story module */
(()=>{
const T={1:'귀환',2:'빈자리',3:'검은 연구실',4:'델타의 잔재',5:'백사의 흔적',6:'프로토타입',7:'내부의 적',8:'블랙 코어'};
const P={maxHp:1000,atk:260,weapon:'킬 오브 킹 전술 블레이드'};
const E={
2:[{name:'본부 경계 요원',hp:700,atk:70,weapon:'전술봉'},{name:'인증 차단 드론',hp:850,atk:80,weapon:'펄스 쇼커'},{name:'보안 집행관',hp:1050,atk:95,weapon:'전술 카빈'}],
3:[{name:'LAB-03 감시기',hp:900,atk:90,weapon:'감시 레이저'},{name:'격리 수호기',hp:1200,atk:105,weapon:'전자 충격포',def:.15}],
4:[{name:'델타 잔당 척후병',hp:1050,atk:100,weapon:'개조 소총'},{name:'델타 기술병',hp:1250,atk:110,weapon:'EMP 랜스'},{name:'델타 강습대장',hp:1650,atk:130,weapon:'중화기'}],
5:[{name:'내부 추적자',hp:1250,atk:115,weapon:'소음 카빈'},{name:'특수 감찰관',hp:1650,atk:135,weapon:'제압 블레이드'}],
6:[{name:'ARC TRACE 프로토타입',hp:2600,atk:160,weapon:'불완전 아크 캐논',def:.20,boss:true}],
7:[{name:'반역 경호대',hp:1450,atk:120,weapon:'전술 소총'},{name:'배신자 집행관',hp:2400,atk:155,weapon:'블랙옵스 블레이드',def:.10,boss:true}],
8:[{name:'BLACK CORE : MK-I',hp:6500,atk:185,weapon:'블랙 코어 캐논',def:.15,boss:true,black:true}]
};
let battle=null;
const $=id=>document.getElementById(id);
function data(){saveData.story??={};saveData.story.stages??={};saveData.story.clearedChapters??={};saveData.story.earth2Data??={};const d=saveData.story.earth2Data;d.arcTraceUnlocked=!!d.arcTraceUnlocked;return d}
const prog=()=>Math.max(0,Math.min(8,+saveData.story?.stages?.earth2||0));
function css(){if($('e2style'))return;const s=document.createElement('style');s.id='e2style';s.textContent=`#earth2-stage-screen{padding:18px}.e2card{background:linear-gradient(180deg,#161820,#0f1117);border:1px solid #343946;border-radius:14px;padding:14px;margin:10px 0;line-height:1.75}.e2sys{font-family:monospace;background:#08090c;border:1px solid #343b48;border-radius:10px;padding:10px;margin:8px 0;color:#a8d8ff;white-space:pre-line}.e2good{color:#78ffad;font-weight:900}.e2bad{color:#ff8797;font-weight:900}.e2gold{color:#ffe26f;font-weight:900}.e2fighters{display:flex;gap:8px}.e2fighter{flex:1;text-align:center;background:#0b0d12;border:1px solid #343b48;border-radius:11px;padding:9px;min-width:0}.e2hp{height:14px;background:#333944;border-radius:8px;overflow:hidden;margin:6px 0}.e2fill{height:100%;background:#48c982}.e2fill.enemy{background:#df4f62}.e2log{height:175px;overflow:auto;background:#06070a;border-radius:10px;padding:9px;font-size:.78rem;line-height:1.5;margin:10px 0}.e2intent{border:1px solid #53617a;border-radius:10px;padding:9px;text-align:center;background:#121724;margin:8px 0}.e2actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.e2actions .btn{margin:0}.e2trace{background:#1b1608;border:1px solid #806b21;border-radius:10px;padding:8px;text-align:center;margin:8px 0}`;document.head.appendChild(s)}
function screen(){css();let e=$('earth2-stage-screen');if(!e){e=document.createElement('div');e.id='earth2-stage-screen';e.className='screen';$('app')?.appendChild(e)}return e}
function show(h){screen().innerHTML=h;showScreen('earth2-stage-screen')}
function btn(t,f,c='btn btn-gold'){const id='e2'+Math.random().toString(36).slice(2);setTimeout(()=>{const b=$(id);if(b)b.onclick=f},0);return`<button id="${id}" class="${c}">${t}</button>`}
const top=(n,sub='')=>`<h2 style="text-align:center">🌎 5-${n} · ${T[n]}</h2><p style="text-align:center;opacity:.7;font-size:.8rem">${sub}</p>`;
const back=()=>btn('← 스테이지 목록',()=>{battle=null;openStoryChapter('earth2')},'btn');
function save(){try{persistSave()}catch(e){console.warn(e)}}
function complete(n,text){data();saveData.story.stages.earth2=Math.max(prog(),n);if(n>=8)saveData.story.clearedChapters.earth2=true;save();show(`${top(n)}<div class="e2card">${text}<div class="e2good" style="text-align:center;font-size:1.2rem;margin-top:12px">STAGE CLEAR</div></div>${n<8?btn(`다음 · 5-${n+1} ${T[n+1]}`,()=>openStoryStage('earth2',n+1),'btn btn-success'):''}${back()}`)}
function chapter(){const c=prog();$('story-title').textContent='🌎 지구 II';$('story-subtitle').textContent='8개 스테이지 · 순차 진행';$('story-back-btn').textContent='← 챕터 선택으로';let h='';for(let i=1;i<=8;i++){const done=i<=c,u=storyStageUnlocked('earth2',i);h+=`<button class="btn" ${u?`onclick="openStoryStage('earth2',${i})"`:'disabled'} style="text-align:left;padding:16px 17px;margin:8px 0;min-height:82px;${done?'border:1px solid #75ffad':''}"><b>${done?'✅':u?'▶️':'🔒'} 5-${i} ${T[i]}</b><div style="font-size:.78rem;opacity:.72;margin-top:7px">${done?'클리어 완료':u?'도전 가능':'앞 스테이지 클리어 필요'}</div></button>`}$('story-list').innerHTML=h}
function intentFor(e){if(e.black){const r=e.hp/e.max;if(r>.65)return Math.random()<.55?'attack':'charge';if(r>.30){const x=Math.random();return x<.34?'guard':x<.67?'attack':'charge'}return Math.random()<.72?'charge':'attack'}const x=Math.random();return x<.42?'attack':x<.70?'guard':'charge'}
const intentName=i=>i==='attack'?'⚔ 공격 준비':i==='guard'?'🛡 방어 태세':'⚡ 충전 중';
const counterTip=i=>i==='attack'?'방어가 유리':i==='guard'?'침투가 유리':'공격으로 끊기';
function startBattle(stage,enemies,after,opt={}){const p={max:P.maxHp,hp:P.maxHp,atk:P.atk,weapon:P.weapon};battle={stage,enemies:enemies.map(x=>({...x,max:x.hp})),idx:0,p,after,trace:0,traceReady:false,log:[],opt,mode:''};nextEnemy()}
function nextEnemy(){if(!battle)return;if(battle.idx>=battle.enemies.length){const a=battle.after;battle=null;a?.();return}battle.e=battle.enemies[battle.idx];battle.e.intent=intentFor(battle.e);battle.log.push(`${battle.e.name} 등장 · ${battle.e.weapon}`);renderBattle()}
function lg(x){battle?.log.push(x)}
function gainTrace(){if(!battle||!data().arcTraceUnlocked)return;battle.trace=Math.min(3,battle.trace+1);lg(`ARC TRACE 동기화 ${battle.trace}/3`);if(battle.trace>=3){battle.traceReady=true;lg('⚡ ARC TRACE READY')}}
function modeText(e){if(!e.black)return'';const r=e.hp/e.max;if(r>.65)return'ASSAULT MODE';if(r>.30)return'DEFENSE MODE';return'OVERLOAD MODE'}
function renderBattle(){if(!battle)return;const b=battle,p=b.p,e=b.e,m=modeText(e);if(m&&m!==b.mode){b.mode=m;lg(`BLACK CORE · ${m}`)}show(`${top(b.stage)}<div class="e2card"><div class="e2fighters"><div class="e2fighter"><b>주인공</b><div style="font-size:.72rem">${p.weapon} · ATK ${p.atk}</div><div class="e2hp"><div class="e2fill" style="width:${Math.max(0,p.hp/p.max*100)}%"></div></div>${Math.max(0,Math.ceil(p.hp))}/${p.max}</div><div class="e2fighter"><b>${e.name}</b><div style="font-size:.72rem">${e.weapon} · ATK ${e.atk}</div><div class="e2hp"><div class="e2fill enemy" style="width:${Math.max(0,e.hp/e.max*100)}%"></div></div>${Math.max(0,Math.ceil(e.hp))}/${e.max}</div></div><div class="e2intent"><b>${intentName(e.intent)}</b><div style="font-size:.74rem;opacity:.72;margin-top:4px">${counterTip(e.intent)}</div></div>${data().arcTraceUnlocked?`<div class="e2trace">ARC TRACE · ${b.trace}/3 ${b.traceReady?'· <b class="e2gold">READY</b>':''}</div>`:'<div class="e2trace" style="opacity:.55">ARC TRACE · 미해금</div>'}<div class="e2log">${b.log.slice(-14).map(x=>`<div>${x}</div>`).join('')}</div><div class="e2actions">${btn('⚔ 공격',()=>act('attack'),'btn btn-danger')}${btn('🛡 방어',()=>act('defend'),'btn')}${btn('🕶 침투',()=>act('infiltrate'),'btn btn-super')}${data().arcTraceUnlocked?(b.traceReady?btn('⚡ ARC TRACE ×5',()=>act('trace'),'btn btn-gold'):btn('ARC TRACE 충전 필요',()=>{},'btn')):btn('ARC TRACE 미해금',()=>{},'btn')}</div></div>${back()}`);const l=document.querySelector('.e2log');if(l)l.scrollTop=l.scrollHeight}
function act(type){if(!battle)return;const b=battle,p=b.p,e=b.e,int=e.intent;let correct=false,enemyCancelled=false,guarding=false,dm=0;
 if(type==='trace'&&b.traceReady){dm=p.atk*5;b.traceReady=false;b.trace=0;lg(`⚡ ARC TRACE · ${dm} 피해`)}
 else if(type==='attack'){const base=Math.round(p.atk*(1-(e.def||0)));if(int==='charge'){correct=true;enemyCancelled=true;dm=base;lg('충전 끊기 성공')}else if(int==='guard'){dm=Math.round(base*.40);lg('방어 태세에 공격 · 피해 감소')}else{dm=base;lg(`공격 · ${dm} 피해`)}}
 else if(type==='defend'){guarding=true;if(int==='attack'){correct=true;dm=Math.round(p.atk*.45);lg(`방어 반격 · ${dm} 피해`)}else lg('방어 자세')}
 else if(type==='infiltrate'){if(int==='guard'){correct=true;dm=Math.round(p.atk*1.40);lg(`방어 침투 성공 · ${dm} 피해`)}else{dm=Math.round(p.atk*.75);lg(`침투 공격 · ${dm} 피해`)}}
 if(dm){e.hp-=dm;if(e.hp<=0){if(correct)gainTrace();lg(`${e.name} 격파`);battle.idx++;return setTimeout(nextEnemy,320)}}
 if(correct)gainTrace();resolveEnemy(enemyCancelled,guarding,type);}
function resolveEnemy(cancelled,guarding,type){if(!battle)return;const b=battle,p=b.p,e=b.e,int=e.intent;if(cancelled){lg('적 행동 취소');return finishTurn()}if(int==='guard'){lg('적은 방어 태세를 유지했다');return finishTurn()}let mult=int==='charge'?1.8:1;if(e.black&&modeText(e)==='OVERLOAD MODE'&&int==='charge')mult=2.15;let damage=Math.round(e.atk*mult);if(guarding&&int==='attack'){damage=Math.round(damage*.35);lg('정확한 방어 · 피해 65% 감소')}else if(guarding)damage=Math.round(damage*.65);p.hp-=damage;lg(`${e.name} → ${damage} 피해`);if(p.hp<=0)return defeat();finishTurn()}
function finishTurn(){if(!battle)return;battle.e.intent=intentFor(battle.e);renderBattle()}
function defeat(){const s=battle.stage;battle=null;show(`${top(s)}<div class="e2card e2bad" style="text-align:center;font-size:1.2rem">DEFEAT</div>${btn('다시 도전',()=>openStoryStage('earth2',s),'btn btn-danger')}${back()}`)}
function branchText(){const c=saveData.story?.earth1BSHChoice;return c==='release'?{choice:'release',text:'과거에 풀어준 B.S.H가 익명 통신으로 접근 키를 보낸다.\n\n“이번엔 내가 빚을 갚지.”'}:{choice:'handover',text:'과거에 넘긴 B.S.H의 이송기록이 검은 연구실에서 끊겨 있다.\n\n누군가 그를 내부 조사에 이용한 흔적만 남아 있다.'}}
function s1(){show(`${top(1,'원래 시대 · 킬 오브 킹 본부')}<div class="e2card">시간 통로가 닫힌다.<br><br>주인공은 약 100년 뒤에서 가져온 <b>파괴된 아크 코어 파편</b>과 함께 원래 시대 지구로 돌아온다.<div class="e2sys">ARC CORE : DESTROYED<br>FUTURE COMBAT SYSTEM : OFFLINE</div>미래형 전투복과 오버레이 반중력포는 코어 파괴로 정상출력이 불가능하다.<br><br>킬 오브 킹 연구팀은 코어 복구 대신 <b>원리 역설계</b>를 시작한다.</div>${btn('본부로 복귀한다',()=>complete(1,'주인공의 귀환은 최고 등급 보안사항으로 봉인된다.'))}${back()}`)}
function s2(){show(`${top(2,'귀환자 인증 실패')}<div class="e2card">주인공의 신분기록은 장기 실종 처리되어 있다.<br><br>본부 자동보안과 일부 경계요원은 주인공을 침입자로 판정한다.<div class="e2sys">OPERATIVE ID : EXPIRED<br>ACCESS : DENIED</div>주인공은 살상 없이 중앙 통제실까지 돌파해야 한다.</div>${btn('본부 경계를 돌파',()=>startBattle(2,E[2],()=>complete(2,'본부 지휘부가 주인공의 신원을 최종 확인한다.'),{}),'btn btn-danger')}${back()}`)}
function s3(){show(`${top(3,'허가되지 않은 연구')}<div class="e2card">아크 코어 파편을 맡긴 연구실과 별개로, 본부 지하에서 승인되지 않은 전력 사용 기록이 발견된다.<div class="e2sys">PROJECT : BLACK<br>AUTHORIZATION : UNKNOWN</div>내부 감시 시스템이 주인공의 접근을 차단한다.</div>${btn('검은 연구실 진입',()=>startBattle(3,E[3],()=>{data().arcTraceUnlocked=true;complete(3,'파편 연구 로그에서 <b>ARC TRACE</b>를 발견한다.<br><br>완전한 타이탄은 복원할 수 없지만, 적의 행동을 분석해 순간적으로 출력을 증폭하는 기술이다.<br><b>정확한 대응 3회 → ARC TRACE ×5</b>')},{}),'btn btn-danger')}${back()}`)}
function s4(){show(`${top(4,'사라졌던 기술')}<div class="e2card">검은 연구실의 부품 목록에서 델타 I 당시 확보됐던 특수무기 규격이 발견된다.<br><br>추적 끝에 폐쇄된 물류기지에서 델타 잔당과 킬 오브 킹 내부 물자가 동시에 발견된다.<br><br>누군가 두 조직의 기술을 연결하고 있다.</div>${btn('델타 잔당 제압',()=>startBattle(4,E[4],()=>complete(4,'델타 잔당이 사용한 장비 일부에 아크 코어 파편과 동일한 역설계 회로가 들어 있다.'),{}),'btn btn-danger')}${back()}`)}
function s5(){const x=branchText();const es=x.choice==='release'?[{...E[5][0],hp:1000},{...E[5][1],hp:1400}]:E[5];show(`${top(5,'과거의 선택')}<div class="e2card" style="white-space:pre-line">${x.text}<br><br>추적 경로 끝에서 내부 감찰팀과 충돌한다.${x.choice==='release'?'<br><span class="e2good">B.S.H의 접근 키로 적 보안장비가 약화된다.</span>':''}</div>${btn('흔적을 추적한다',()=>startBattle(5,es,()=>complete(5,x.choice==='release'?'B.S.H가 남긴 자료에서 검은 프로젝트의 책임자가 킬 오브 킹 내부 인물임을 확인한다.':'B.S.H 이송기록을 조작한 서명이 검은 프로젝트 승인기록과 일치한다.'),{}),'btn btn-danger')}${back()}`)}
function s6(){show(`${top(6,'ARC TRACE 실전형')}<div class="e2card">검은 프로젝트 연구동에서 불완전한 미래기술 병기가 가동된다.<div class="e2sys">PROTOTYPE ONLINE<br>ARC COMPATIBILITY : 12%</div>타이탄을 흉내 냈지만 안정성이 극도로 낮다.</div>${btn('프로토타입 파괴',()=>startBattle(6,E[6],()=>complete(6,'프로토타입의 코어에는 델타 기술과 미래 아크 회로가 동시에 사용됐다.<br><br>제작자는 미래기술의 존재를 이미 알고 있었던 것처럼 보인다.'),{}),'btn btn-danger')}${back()}`)}
function s7(){show(`${top(7,'킬 오브 킹 내부')}<div class="e2card">검은 프로젝트 승인자를 추적한 끝에 내부 작전국의 고위 집행관이 드러난다.<br><br><span class="e2gold">집행관</span><br>“미래를 봤다면 이해할 텐데. 우리가 먼저 가져야 살아남는다.”<br><br>그는 아크 파편과 델타 기술을 모두 지하 격납고로 옮긴다.</div>${btn('배신자를 추격',()=>startBattle(7,E[7],()=>complete(7,'집행관을 제압하지만 이미 최종 병기 가동 명령이 내려갔다.<div class="e2sys">BLACK CORE : BOOT SEQUENCE</div>'),{}),'btn btn-danger')}${back()}`)}
function s8(){show(`${top(8,'BLACK PROJECT')}<div class="e2card">지하 격납고 중앙에서 거대한 코어 병기가 깨어난다.<div class="e2sys">BLACK CORE : MK-I<br>ASSAULT / DEFENSE / OVERLOAD</div>미래 아크 기술과 델타 특수무기를 억지로 결합한 불완전 병기.<br><br>코어 외벽에는 고대의 가면에서 보았던 것과 유사한 문양이 새겨져 있다.<br><span style="opacity:.75">하지만 그 문양의 정체는 아직 알 수 없다.</span></div>${btn('BLACK CORE : MK-I 파괴',()=>startBattle(8,E[8],()=>complete(8,'블랙 코어가 붕괴한다.<br><br>파괴 직전 코어가 정체불명의 좌표로 신호를 송신한다.<div class="e2sys">SIGNAL DESTINATION : UNKNOWN<br>THERMAL SIGNATURE : NON-HUMAN</div>지하 공간에 잠시 검은 균열이 열렸다 사라진다.<br><br><b>마계 I로 이어진다.</b>'),{}),'btn btn-danger')}${back()}`)}
const oldRC=window.renderStoryChapter;window.renderStoryChapter=function(id){if(id==='earth2')return chapter();return oldRC?.apply(this,arguments)};
const oldOS=window.openStoryStage;window.openStoryStage=function(ch,n){if(ch!=='earth2')return oldOS?.apply(this,arguments);if(!storyStageUnlocked('earth2',n))return alert('앞 스테이지를 먼저 클리어하세요.');battle=null;[0,s1,s2,s3,s4,s5,s6,s7,s8][+n]?.()};
window.LREarth2={getPlayerStats:()=>({...P}),getEnemyStats:()=>JSON.parse(JSON.stringify(E)),getProgress:prog,getBSHChoice:()=>saveData.story?.earth1BSHChoice||null};
})();
