/* Lost Ruby - Future I bug/balance runtime patch v2 */
(()=>{
const T=['','시간의 역전','오버드라이브','콘스탄티노폴리스','아크 지구','예루살렘','아틀란티스','달','타임오버'];
const TR=['','시간칩','오버드라이브 엔진','시간 코어','아크 셀','성지순례','심해 결정체','월석 파편','시간선의 초월'];
const GN=['없음','낡은','평범','최고급'];
const E={1:[['정찰 드론',220,35,'펄스 레이저'],['보안 드론',320,45,'전기 충격탄',0,.15]],4:[['중장갑 수호기',1100,110,'이온 라이플'],['저거너트 슬레이어',1600,130,'충격포',.2],['아크 집행자',2300,160,'아크 캐논',0,0,3]],6:[['아틀란티스 프라임',1700,150,'수압 라이플'],['아셔 거행자',2600,190,'압력창',.2],['아틀란티스 수호자',4200,240,'심해 파동포',0,0,3]]};
let b=null,q=null,tr=null,busy=false;const $=x=>document.getElementById(x);
function d(){saveData.story??={};saveData.story.stages??={};saveData.story.clearedChapters??={};saveData.story.future1Data??={};const x=saveData.story.future1Data;x.treasures??={};x.lpRewarded??={};for(let i=1;i<=8;i++)x.treasures[i]=Math.max(0,Math.min(3,+x.treasures[i]||0));x.coreDestroyed=!!x.coreDestroyed;return x}
const pg=()=>Math.max(0,Math.min(8,+saveData.story?.stages?.future1||0));const cnt=()=>{let n=0;for(let i=1;i<=8;i++)if(d().treasures[i]>0)n++;return n};
function bm(){const a=[1,2,3,4,5,6].map(i=>d().treasures[i]);return a.every(x=>x>=3)?1:a.every(x=>x>=2)?5:a.every(x=>x>=1)?10:100}function bs(){const m=bm();return{m,hp:80000*m,atk:3000*m}}
function hp(){return Math.round(800*(1+(d().treasures[1]===3?.05:0)+(d().treasures[4]===3?.10:0)))}
function w(s){return s>=7?{name:'오버레이 반중력포',atk:350,type:'overlay'}:s>=4?{name:'레이저 쌍권총',atk:150,type:'dual'}:{name:'백사의 침 +5',atk:35,type:'needle'}}
const atk=s=>Math.round(w(s).atk*(1+cnt()*.15));const titan=s=>s>=4&&s<=7;const arc=s=>s>=5&&s<=7;
function css(){if($('f1fixcss'))return;const s=document.createElement('style');s.id='f1fixcss';s.textContent='#future1-stage-screen{padding:18px}.f1s{background:linear-gradient(180deg,#12213b,#0c1224);border-left:3px solid #69b8ff;border-radius:14px;padding:16px;margin:10px 0;line-height:1.8;white-space:pre-line}.f1sys{font-family:monospace;color:#a8ddff;background:#080d18;border:1px solid #29466d;border-radius:10px;padding:10px;margin:9px 0;white-space:pre-line}.f1box{background:#10172a;border:1px solid #293b5d;border-radius:14px;padding:13px;margin:9px 0}.f1gold{color:#ffe26f;font-weight:900}.f1good{color:#75ffad;font-weight:900}.f1bad{color:#ff8797;font-weight:900}.f1hp{height:14px;background:#333a4b;border-radius:8px;overflow:hidden;margin:5px}.f1fill{height:100%;background:#43c47b}.f1fill.e{background:#df4a59}.f1fighters{display:flex;gap:8px}.f1fighter{flex:1;text-align:center;background:#0b1020;border:1px solid #31466b;border-radius:11px;padding:9px}.f1log{height:170px;overflow:auto;background:#070b13;border-radius:10px;padding:9px;font-size:.78rem;line-height:1.5;margin:10px 0}.f1q{height:62px;position:relative;background:#070b13;border-radius:10px;overflow:hidden;margin:10px 0}.f1z{position:absolute;left:42%;width:16%;height:100%;background:#245b42}.f1p{position:absolute;left:47%;width:6%;height:100%;background:#786d28}.f1c{position:absolute;width:5px;height:100%;background:#fff}.f1trial{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}';document.head.appendChild(s)}
function scr(){css();let e=$('future1-stage-screen');if(!e){e=document.createElement('div');e.id='future1-stage-screen';e.className='screen';$('app')?.appendChild(e)}return e}function show(h){scr().innerHTML=h;showScreen('future1-stage-screen')}
function bt(t,f,c='btn btn-gold'){const id='fx'+Math.random().toString(36).slice(2);setTimeout(()=>{$(id)&&( $(id).onclick=f)},0);return`<button id="${id}" class="${c}">${t}</button>`}const top=(n,x='')=>`<h2 style="text-align:center">🌆 4-${n} · ${T[n]}</h2><p style="text-align:center;opacity:.7;font-size:.8rem">${x}</p>`;
function stop(){if(q?.tm)clearInterval(q.tm);q=null;b=null;tr=null;if(typeof stopFutureStageBgm==='function')stopFutureStageBgm()}const back=()=>bt('← 스테이지 목록',()=>{stop();openStoryChapter('future1')},'btn');
function roll(n){const x=d(),o=x.treasures[n],r=Math.random(),g=r<.1?3:r<.3?2:r<.65?1:0;let first=false;if(g>o){x.treasures[n]=g;first=o===0}return{g,cur:x.treasures[n],first}}
const cloud=()=>typeof useCloud!=='undefined'&&useCloud&&typeof fbDb!=='undefined'&&fbDb&&typeof fbUserId!=='undefined'&&fbUserId;
function fd(o){o.story??={};o.story.stages??={};o.story.clearedChapters??={};o.story.future1Data??={};const x=o.story.future1Data;x.treasures??={};x.lpRewarded??={};return x}
async function lp(n){const add=n===7?50:n===8?100:0,x=d();if(!add||x.lpRewarded[n])return 0;if(!cloud()){x.lpRewarded[n]=true;saveData.lp=Math.max(0,+saveData.lp||0)+add;return add}let out=null;const ref=fbDb.collection('profiles').doc(fbUserId);await fbDb.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw Error('PROFILE_NOT_FOUND');const p=s.data()||{},base=Object.assign(defaultSaveData(p.nick||saveData.nick||''),p.data||{}),z=fd(base),now=d();base.story.stages.future1=Math.max(+base.story.stages.future1||0,pg());if(base.story.stages.future1>=8)base.story.clearedChapters.future1=true;for(let i=1;i<=8;i++)z.treasures[i]=Math.max(+z.treasures[i]||0,+now.treasures[i]||0);z.coreDestroyed=!!(z.coreDestroyed||now.coreDestroyed);let v=Math.max(0,+(p.lp!==undefined?p.lp:base.lp)||0),ok=false;if(!z.lpRewarded[n]){z.lpRewarded[n]=true;v+=add;ok=true}base.lp=v;base.lr=Math.max(0,+(p.lr!==undefined?p.lr:base.lr)||0);tx.set(ref,{nick:base.nick||p.nick||'',lr:base.lr,lp:v,data:base,updated_at:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});out={base,ok}});if(out){saveData=Object.assign(defaultSaveData(out.base.nick||saveData.nick||''),out.base);d().lpRewarded[n]=true}return out?.ok?add:0}
async function clear(n,text){if(busy)return;busy=true;try{saveData.story.stages.future1=Math.max(pg(),n);if(n>=8){saveData.story.clearedChapters.future1=true;d().coreDestroyed=true}const r=roll(n);let gain=0,err=false;if((n===7||n===8)&&r.cur===3&&!d().lpRewarded[n])try{gain=await lp(n)}catch(e){console.warn(e);err=true}let badge=false;if([1,2,3,4,5,6,7,8].every(i=>d().treasures[i]===3))try{badge=!!unlockBadge('future_treasure_master')}catch(_){}try{persistSave()}catch(_){}let z=r.g?`${GN[r.g]} ${TR[n]} 등장`:'보물 없음';if(r.cur>r.g&&r.g)z+=` · 기존 ${GN[r.cur]} 유지`;if(r.first)z+='<br><span class="f1good">최초 획득 · 미래편 공격력 +15%</span>';if(gain)z+=`<br><b>LP +${gain}</b>`;if(err)z+='<br><span class="f1bad">LP 지급 실패 · 다음 클리어 때 재시도</span>';if(badge)z+='<br>🏅 시간선의 정복자';show(`${top(n)}<div class="f1s">${text}<div class="f1good" style="text-align:center;font-size:1.2rem">STAGE CLEAR</div></div><div class="f1box f1gold" style="text-align:center">💎 ${z}<div style="font-size:.72rem;opacity:.7">없음 35% · 낡은 35% · 평범 20% · 최고급 10%</div></div>${n<8?bt(`다음 · 4-${n+1} ${T[n+1]}`,()=>openStoryStage('future1',n+1),'btn btn-success'):''}${back()}`)}finally{busy=false}}
function chapter(){const c=pg();$('story-title').textContent='🌆 미래 I';$('story-subtitle').textContent='8개 스테이지 · 순차 진행';$('story-back-btn').textContent='← 챕터 선택으로';let h='';for(let i=1;i<=8;i++){const done=i<=c,u=storyStageUnlocked('future1',i);h+=`<button class="btn" ${u?`onclick="openStoryStage('future1',${i})"`:'disabled'} style="text-align:left;padding:16px 17px;margin:8px 0;min-height:82px;${done?'border:1px solid #75ffad':''}"><b>${done?'✅':u?'▶️':'🔒'} 4-${i} ${T[i]}</b><div style="font-size:.78rem;opacity:.72;margin-top:7px">${done?'클리어 완료':u?'도전 가능':'앞 스테이지 클리어 필요'}</div></button>`}$('story-list').innerHTML=h}
function start(s,arr,after,boss=false){const ww=w(s),p={max:hp(),hp:hp(),atk:atk(s),w:ww,rev:false,para:false};b={s,es:arr.map(a=>({name:a[0],hp:a[1],max:a[1],atk:a[2],w:a[3],def:a[4]||0,para:a[5]||0,heavy:a[6]||0})),i:0,p,after,boss,guard:boss&&d().treasures[6]===3?2:0,t:0,used:false,arcCheck:false,turn:0,log:[]};enc()}
function enc(){if(!b)return;if(b.i>=b.es.length){const f=b.after;b=null;f?.();return}b.e=b.es[b.i];b.turn=0;b.log.push(`${b.e.name} 등장 · ${b.e.w}`);rb()}function lg(x){b?.log.push(x)}
function rb(){if(!b)return;const p=b.p,e=b.e,tm=arc(b.s)?30:15;show(`${top(b.s)}<div class="f1box"><div class="f1fighters"><div class="f1fighter"><b>주인공 ${b.t?'⚡':''}</b><div style="font-size:.72rem">${p.w.name} · ATK ${p.atk}${b.t?' ×'+tm:''}</div><div class="f1hp"><div class="f1fill" style="width:${Math.max(0,p.hp/p.max*100)}%"></div></div>${Math.max(0,Math.ceil(p.hp))}/${p.max}</div><div class="f1fighter"><b>${e.name}</b><div style="font-size:.72rem">${e.w} · ATK ${e.atk.toLocaleString()}</div><div class="f1hp"><div class="f1fill e" style="width:${Math.max(0,e.hp/e.max*100)}%"></div></div>${Math.max(0,Math.ceil(e.hp)).toLocaleString()}/${e.max.toLocaleString()}</div></div><div class="f1log">${b.log.slice(-14).map(x=>`<div>${x}</div>`).join('')}</div>${bt(p.para?'마비됨':'공격',hit,p.para?'btn':'btn btn-danger')}${titan(b.s)&&!b.used?bt(`⚡ ${arc(b.s)?'ARC TITAN ×30':'TITAN ×15'} · 3턴`,use,'btn btn-super'):''}</div>${back()}`)}function use(){if(!b||b.used||!titan(b.s))return;b.used=true;b.t=3;lg(arc(b.s)?'ARC CORE · OVERLAY MODE ×30':'TITAN CORE · LIMIT RELEASE ×15');rb()}function consume(){if(b?.t>0){b.t--;if(!b.t)lg('TITAN CORE OUTPUT : 0%')}}
function hit(){if(!b)return;const p=b.p,e=b.e;if(p.para){p.para=false;lg('⚡ 마비로 행동 불가');return enemy()}let dm=p.atk*(b.t?(arc(b.s)?30:15):1);if(p.w.type==='overlay'&&Math.random()<.2){dm=Math.round(dm*1.8);lg('🌀 중력 붕괴 · 1.8배')}if(e.def)dm=Math.round(dm*(1-Math.max(0,e.def-(p.w.type==='overlay'?.3:0))));e.hp-=dm;lg(`주인공 ${dm.toLocaleString()} 피해`);if(p.w.type==='overlay'&&e.hp>0&&Math.random()<.1){e.lock=true;lg('🔒 GRAVITY LOCK · 적 1턴 봉쇄')}if(e.hp<=0){consume();return down()}enemy()}
function enemy(){if(!b)return;const p=b.p,e=b.e;if(e.lock){e.lock=false;lg('중력 제압으로 적 행동 불가');return end()}if(b.guard){b.guard--;lg('🌊 파도의 수호 · 공격 완전 방어');return end()}if(Math.random()<.15){lg('💨 미래형 전투복 · 회피');return end()}b.turn++;let raw=e.atk;if(e.heavy&&b.turn%e.heavy===0){raw*=2;lg('⚠ 강화 포격')}const dm=Math.round(raw*.4);p.hp-=dm;lg(`${e.name} ${dm.toLocaleString()} 피해 (전투복 60% 감소)`);if(e.para&&Math.random()<e.para){p.para=true;lg('⚡ 전기 충격 · 마비')}if(p.hp>0&&b.t&&arc(b.s)&&!b.arcCheck&&p.hp/p.max<.15){b.arcCheck=true;lg('ARC CORE CRITICAL · HP 15% 미만');if(Math.random()<.5){e.hp=0;lg('💥 반중력 폭발 · 상대 즉사');consume();rb();return setTimeout(down,400)}lg('반중력 폭발 실패')}if(p.hp<=0){if(d().treasures[5]===3&&!p.rev){p.rev=true;p.hp=Math.max(1,Math.round(p.max*.3));lg('✦ 성지순례 · HP 30% 부활')}else return lose()}end()}function end(){consume();rb()}function down(){if(!b)return;lg(`${b.e.name} 격파`);b.i++;setTimeout(enc,300)}function lose(){const s=b.s;b=null;show(`${top(s)}<div class="f1box f1bad" style="text-align:center">DEFEAT</div>${bt('다시 도전',()=>openStoryStage('future1',s),'btn btn-danger')}${back()}`)}
function qstop(){if(q?.tm)clearInterval(q.tm);q=null}function qstart(){qstop();q={r:1,hp:3,ok:0,pos:0,dir:1,lock:false,shield:0};qround()}function qround(){if(!q)return;if(q.r>6){const n=q.ok;qstop();return clear(2,`네온 고속도로 추격을 돌파한다.<br><br>오토바이 무장 슬롯의 <b>레이저 쌍권총</b>을 챙긴다.<br><br>QTE 성공 ${n}/6`)}q.lock=false;show(`${top(2,'OVERDRIVE CITY')}<div class="f1box">초록 구간에서 회피!<div class="f1q"><div class="f1z"></div><div class="f1p"></div><div id="f1cursor" class="f1c"></div></div><button id="f1qb" class="btn btn-super">🏍️ 지금 회피!</button><div id="f1qs" style="text-align:center;font-size:.78rem">${q.r}/6 · 내구도 ${q.hp}/3${q.shield?' · 🛡️ PERFECT 보호막':''}</div></div>${back()}`);$('f1qb').onclick=qhit;q.tm=setInterval(()=>{if(!q)return;q.pos+=q.dir*2.3;if(q.pos>99){q.pos=99;q.dir=-1}if(q.pos<0){q.pos=0;q.dir=1}const c=$('f1cursor');if(c)c.style.left=q.pos+'%'},24)}function qhit(){if(!q||q.lock)return;q.lock=true;if(q.tm)clearInterval(q.tm);$('f1qb').disabled=true;const ok=q.pos>=42&&q.pos<=58,perf=q.pos>=47&&q.pos<=53,s=$('f1qs');if(ok){q.ok++;if(perf){q.shield=1;s.innerHTML='<span class="f1good">PERFECT · 다음 피격 1회 무효</span>'}else s.innerHTML='<span class="f1good">회피 성공</span>'}else if(q.shield){q.shield=0;s.innerHTML='<span class="f1good">PERFECT 보호막 · 피격 무효</span>'}else{q.hp--;s.innerHTML='<span class="f1bad">피격 · 내구도 -1</span>'}if(q.hp<=0)return setTimeout(()=>{qstop();show(`${top(2)}<div class="f1box f1bad">CRASH</div>${bt('다시 도전',qstart,'btn btn-danger')}${back()}`)},350);q.r++;setTimeout(qround,420)}
const TM={3:['기록 해킹',['A7','K3','T9']],5:['유물 탐색',['◇','△','✦']],8:['시간 좌표 동기화',['α','β','Ω']]};function story(n,text){if(pg()<n)return clear(n,text);const m=TM[n];tr={n,text,r:1,target:'',m};trial()}function trial(){if(!tr)return;const a=tr.m[1];tr.target=a[Math.random()*a.length|0];const opts=[...a].sort(()=>Math.random()-.5);show(`${top(tr.n,tr.m[0])}<div class="f1box"><b>${tr.m[0]} · ${tr.r}/3</b><div style="text-align:center;font-size:2rem;color:#ffe26f;padding:14px">${tr.target}</div><div class="f1trial">${opts.map(v=>bt(v,()=>pick(v),'btn')).join('')}</div><div id="trmsg" style="text-align:center"></div></div>${back()}`)}function pick(v){if(!tr)return;if(v!==tr.target){$('trmsg').innerHTML='<span class="f1bad">불일치</span>';return setTimeout(trial,400)}tr.r++;if(tr.r>3){const n=tr.n,t=tr.text;tr=null;return setTimeout(()=>clear(n,t),300)}setTimeout(trial,300)}
function s1(){show(`${top(1,'CHRONO PANIC')}<div class="f1s">고대의 가면이 폭주한 뒤 약 100년 뒤 미래도시에서 눈을 뜬다.<br><br>보안 시스템이 신원불명자를 감지한다.<div class="f1sys">UNKNOWN CITIZEN DETECTED<br>IDENTITY : NOT FOUND</div>긴급 장비함에서 <b>미래형 전투복</b>을 착용한다.<div class="f1gold">HP +300 · 받는 피해 60% 감소 · 회피 15%</div></div>${bt('보안 드론 돌파',()=>start(1,E[1],()=>clear(1,'도시 전체에 신원불명 경보가 퍼진다.')),'btn btn-danger')}${back()}`)}function s2(){show(`${top(2,'OVERDRIVE CITY')}<div class="f1s">보안부대가 몰려오자 미래형 오토바이를 탈취한다.<br><br>네온 고속도로 레이저 추격전이 시작된다.</div>${bt('🏍️ 오버드라이브',qstart,'btn btn-super')}${back()}`)}function s3(){show(`${top(3)}<div class="f1s">콘스탄티노폴리스 기록도시.<div class="f1sys">KILL OF KING · DISBANDED<br>OPERATIVE · MISSING</div>최심부에서 <b>타이탄 코어</b>를 연결한다.<div class="f1gold">전투당 1회 · 3턴 · 공격력 ×15</div></div>${bt(pg()>=3?'기록 재탐색':'타이탄 코어 장착',()=>story(3,'타이탄 시스템이 활성화된다.'))}${back()}`)}function s4(){show(`${top(4)}<div class="f1s">아크 지구 중앙 연구시설.<div class="f1sys">ARC CORE SIGNAL DETECTED<br>SECURITY LEVEL : MAXIMUM</div>아크 집행자가 중앙 코어를 지킨다.</div>${bt('아크 시설 돌파',()=>start(4,E[4],()=>clear(4,'아크 코어 동기화.<br><b>ARC TITAN · 공격력 ×30 · 3턴</b>')),'btn btn-danger')}${back()}`)}function s5(){show(`${top(5)}<div class="f1s">예루살렘 역사 데이터 보관소. 고대의 가면과 비슷한 문양이 남아 있지만 핵심 기록은 지워져 있다.</div>${bt(pg()>=5?'성역 재탐색':'성역 조사 완료',()=>story(5,'달 좌표가 아틀란티스에 보관되어 있음을 확인한다.'))}${back()}`)}function s6(){show(`${top(6)}<div class="f1s">해저도시 아틀란티스. 달 기지 좌표는 중앙 코어에 봉인되어 있다.<div class="f1sys">ATLANTIS SECURITY SYSTEM<br>INTRUDER DETECTED</div></div>${bt('중앙 코어 돌파',()=>start(6,E[6],()=>clear(6,'달 좌표와 <b>오버레이 반중력포</b> 획득.<br>ATK 350 · 중력 붕괴 20% · 중력 제압 10% · 방어효과 30% 무시')),'btn btn-danger')}${back()}`)}function s7(){const z=bs();show(`${top(7,'NEON SIGNAL')}<div class="f1s">폐허가 된 월면 시간관측소.<div class="f1sys">IDENTIFICATION<br>노범수 / 월면 시간관측소 책임자<br>NEURAL LIMITER : FAILURE</div><b>폭주한 노범수</b><br>${z.m}배율 · HP ${z.hp.toLocaleString()} · ATK ${z.atk.toLocaleString()}<br><br>4-1~4-6 보물만 배율에 적용.</div>${bt('폭주한 노범수와 전투',()=>start(7,[['폭주한 노범수',z.hp,z.atk,'월면 중력포 · 강화 의수']],()=>clear(7,'노범수가 쓰러지고 시간관측 장치가 해제된다.'),true),'btn btn-danger')}${back()}`)}function s8(){show(`${top(8)}<div class="f1s">시간관측 장치와 고대의 가면을 연결한다.<div class="f1sys">ARC CORE OUTPUT : 147%<br>CORE STRUCTURE FAILURE<br>TIME OVER</div>아크 코어가 파괴된다.<br><b>현재 시간대에서는 타이탄을 더 이상 사용할 수 없다.</b></div>${bt(pg()>=8?'시간 좌표 재탐색':'시간선을 초월한다',()=>story(8,'원래 시대 지구로 귀환한다.<br>킬 오브 킹 본부가 파괴된 아크 코어 연구를 시작한다.<br><b>지구 II로 이어진다.</b>'),'btn btn-super')}${back()}`)}
const oldRC=window.renderStoryChapter;window.renderStoryChapter=function(id){if(id==='future1')return chapter();return oldRC?.apply(this,arguments)};const oldOS=window.openStoryStage;window.openStoryStage=function(ch,n){if(ch!=='future1')return oldOS?.apply(this,arguments);if(!storyStageUnlocked('future1',n))return alert('앞 스테이지를 먼저 클리어하세요.');stop();if(typeof startFutureStageBgm==='function')startFutureStageBgm(+n);[0,s1,s2,s3,s4,s5,s6,s7,s8][+n]?.()};
window.LRFuture1={getBossMultiplier:bm,getBossStats:bs,getTreasureAttackBonus:()=>cnt()*15,getTreasureCount:cnt,getTreasureData:()=>({...d().treasures}),getPlayerStats:(s=7)=>({maxHp:hp(),weapon:w(s),attack:atk(s),damageReduction:.6,evasion:.15,titan:titan(s)?(arc(s)?30:15):0,coreDestroyed:d().coreDestroyed}),getEnemyStats:()=>JSON.parse(JSON.stringify(E)),isCoreDestroyed:()=>d().coreDestroyed};
})();