/* Lost Ruby - Future I production */
(() => {
const T={1:'시간의 역전',2:'오버드라이브',3:'콘스탄티노폴리스',4:'아크 지구',5:'예루살렘',6:'아틀란티스',7:'달',8:'타임오버'};
const TR={1:'시간칩',2:'오버드라이브 엔진',3:'시간 코어',4:'아크 셀',5:'성지순례',6:'심해 결정체',7:'월석 파편',8:'시간선의 초월'};
const GN=['없음','낡은','평범','최고급'];
const BADGE={id:'future_treasure_master',icon:'⏳',name:'시간선의 정복자',desc:'미래 I의 8개 보물을 모두 최고급으로 수집',cat:'story'};
const E={
1:[{name:'정찰 드론',hp:220,atk:35,w:'펄스 레이저'},{name:'보안 드론',hp:320,atk:45,w:'전기 충격탄',para:.15}],
4:[{name:'아크 센트리',hp:1100,atk:110,w:'이온 라이플'},{name:'중장갑 수호기',hp:1600,atk:130,w:'충격포',def:.20},{name:'아크 가디언',hp:2300,atk:160,w:'아크 캐논',heavy:3}],
6:[{name:'아틀란티스 경비병',hp:1700,atk:150,w:'수압 라이플'},{name:'심해 수호기',hp:2600,atk:190,w:'압력창',def:.20},{name:'아틀란티스 수호자',hp:4200,atk:240,w:'심해 파동포',heavy:3}]
};
let battle=null,qte=null;
const $=id=>document.getElementById(id);
function data(){
 if(!saveData.story)saveData.story={}; if(!saveData.story.stages)saveData.story.stages={}; if(!saveData.story.clearedChapters)saveData.story.clearedChapters={};
 if(!saveData.story.future1Data)saveData.story.future1Data={}; const d=saveData.story.future1Data;
 if(!d.treasures)d.treasures={}; for(let i=1;i<=8;i++)d.treasures[i]=Math.max(0,Math.min(3,Number(d.treasures[i])||0));
 if(!d.lpRewarded)d.lpRewarded={}; d.coreDestroyed=!!d.coreDestroyed; return d;
}
function prog(){return Math.max(0,Math.min(8,Number(saveData.story?.stages?.future1)||0));}
function tc(){const d=data();let n=0;for(let i=1;i<=8;i++)if(d.treasures[i]>0)n++;return n;}
function bossM(){const t=data().treasures,a=[1,2,3,4,5,6];if(a.every(i=>t[i]>=3))return 1;if(a.every(i=>t[i]>=2))return 5;if(a.every(i=>t[i]>=1))return 10;return 100;}
function bossS(){const m=bossM();return{m,hp:80000*m,atk:3000*m};}
function maxHp(){const t=data().treasures;return Math.round(800*(1+(t[1]===3?.05:0)+(t[4]===3?.10:0)));}
function weapon(){const p=prog();if(p>=6)return{name:'오버레이 반중력포',atk:350,type:'overlay'};if(p>=2)return{name:'레이저 쌍권총',atk:150,type:'dual'};return{name:'백사의 침 +5',atk:35,type:'needle'};}
function pAtk(){return Math.round(weapon().atk*(1+tc()*.15));}
function titanOK(){return prog()>=3&&!data().coreDestroyed;} function arc(){return prog()>=4&&!data().coreDestroyed;}
function ui(){
 if(!$('future1-style')){const s=document.createElement('style');s.id='future1-style';s.textContent=`#future1-stage-screen{padding:18px}.f1s{background:linear-gradient(180deg,#12213b,#0c1224);border-left:3px solid #69b8ff;border-radius:14px;padding:16px;margin:10px 0;line-height:1.8;white-space:pre-line}.f1sys{font-family:monospace;color:#a8ddff;background:#080d18;border:1px solid #29466d;border-radius:10px;padding:10px;margin:9px 0;white-space:pre-line}.f1box{background:#10172a;border:1px solid #293b5d;border-radius:14px;padding:13px;margin:9px 0}.f1hp{height:14px;background:#333a4b;border-radius:8px;overflow:hidden;margin:5px 0}.f1fill{height:100%;background:#43c47b}.f1fill.e{background:#df4a59}.f1fighters{display:flex;gap:8px}.f1fighter{flex:1;min-width:0;text-align:center;background:#0b1020;border:1px solid #31466b;border-radius:11px;padding:9px}.f1log{height:180px;overflow:auto;background:#070b13;border-radius:10px;padding:9px;font-size:.78rem;line-height:1.5;margin:10px 0}.f1q{height:62px;position:relative;background:#070b13;border-radius:10px;overflow:hidden;margin:10px 0}.f1z{position:absolute;left:42%;width:16%;height:100%;background:#245b42}.f1p{position:absolute;left:47%;width:6%;height:100%;background:#786d28}.f1c{position:absolute;width:5px;height:100%;background:#fff}.f1gold{color:#ffe26f;font-weight:900}.f1good{color:#75ffad;font-weight:900}.f1bad{color:#ff8797;font-weight:900}`;document.head.appendChild(s);}
 let e=$('future1-stage-screen');if(!e){e=document.createElement('div');e.id='future1-stage-screen';e.className='screen';$('app')?.appendChild(e);}return e;
}
function show(h){const e=ui();e.innerHTML=h;showScreen('future1-stage-screen');}
function btn(txt,fn,cls='btn btn-gold'){const id='f1_'+Math.random().toString(36).slice(2);setTimeout(()=>{const b=$(id);if(b)b.onclick=fn},0);return`<button id="${id}" class="${cls}">${txt}</button>`;}
function top(n,sub=''){return`<h2 style="text-align:center">🌆 4-${n} · ${T[n]}</h2><p style="text-align:center;opacity:.7;font-size:.8rem">${sub}</p>`;}
function stopMusic(){if(typeof stopFutureStageBgm==='function')stopFutureStageBgm();}
function back(){return btn('← 스테이지 목록',()=>{stopQ();battle=null;stopMusic();openStoryChapter('future1')},'btn');}
function persist(){try{persistSave()}catch(e){console.warn(e)}}
function addBadge(){try{if(typeof BADGE_DEFS!=='undefined'&&!BADGE_DEFS.some(x=>x.id===BADGE.id))BADGE_DEFS.push(BADGE)}catch(_){}}
addBadge();
function roll(n){const d=data(),old=d.treasures[n],r=Math.random(),g=r<.10?3:r<.30?2:r<.65?1:0;let lp=0,first=false;if(g>old){d.treasures[n]=g;first=old===0;}if(d.treasures[n]===3&&old<3){if(n===7&&!d.lpRewarded[7]){d.lpRewarded[7]=true;saveData.lp=(+saveData.lp||0)+50;lp=50}if(n===8&&!d.lpRewarded[8]){d.lpRewarded[8]=true;saveData.lp=(+saveData.lp||0)+100;lp=100}}
 let badge=false;if([1,2,3,4,5,6,7,8].every(i=>d.treasures[i]===3)){try{badge=!!unlockBadge(BADGE.id)}catch(_){}}return{g,cur:d.treasures[n],first,lp,badge};}
function clear(n,text){stopMusic();if(!saveData.story.stages)saveData.story.stages={};saveData.story.stages.future1=Math.max(prog(),n);if(n>=8){saveData.story.clearedChapters.future1=true;data().coreDestroyed=true}const r=roll(n);persist();let tr=r.g?`${GN[r.g]} ${TR[n]} 등장`:'보물 없음';if(r.cur>r.g&&r.g)tr+=` · 기존 ${GN[r.cur]} 유지`;if(r.first)tr+='<br><span class="f1good">최초 획득 · 미래편 공격력 +15%</span>';if(r.lp)tr+=`<br><b>LP +${r.lp}</b>`;if(r.badge)tr+=`<br>🏅 ${BADGE.name}`;
 const nx=n<8?btn(`다음 · 4-${n+1} ${T[n+1]}`,()=>openStoryStage('future1',n+1),'btn btn-success'):'';show(`${top(n)}<div class="f1s">${text}<div class="f1good" style="text-align:center;font-size:1.2rem;margin-top:12px">STAGE CLEAR</div></div><div class="f1box f1gold" style="text-align:center">💎 ${tr}<div style="font-size:.72rem;opacity:.7;margin-top:5px">없음 35% · 낡은 35% · 평범 20% · 최고급 10%</div></div>${nx}${back()}`);}
function tpanel(){const d=data(),s=bossS();let h='';for(let i=1;i<=8;i++)h+=`<div style="display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #ffffff12"><span>4-${i} ${TR[i]}</span><b>${GN[d.treasures[i]]}</b></div>`;return`<div class="f1box"><b>💎 미래 I 보물</b>${h}<div style="font-size:.75rem;margin-top:8px">획득 ${tc()}/8 · 공격력 +${tc()*15}%<br>노범수 ${s.m}배율 · HP ${s.hp.toLocaleString()} · ATK ${s.atk.toLocaleString()}</div></div>`;}
function renderChapter(){const c=prog();$('story-title').textContent='🌆 미래 I';$('story-subtitle').textContent='8개 스테이지 · 미래편 보물 8종';$('story-back-btn').textContent='← 챕터 선택으로';let h='';for(let i=1;i<=8;i++){const done=i<=c,un=storyStageUnlocked('future1',i);h+=`<button class="btn" ${un?`onclick="openStoryStage('future1',${i})"`:'disabled'} style="text-align:left;margin:6px 0;${done?'border:1px solid #75ffad':''}"><b>${done?'✅':un?'▶️':'🔒'} 4-${i} ${T[i]}</b><div style="font-size:.76rem;opacity:.7">${done?'클리어 완료':un?'도전 가능':'앞 스테이지 클리어 필요'} · 💎 ${GN[data().treasures[i]]}</div></button>`}$('story-list').innerHTML=tpanel()+h;}
function startBattle(stage,enemies,after,boss=false){const p={max:maxHp(),hp:maxHp(),atk:pAtk(),weapon:weapon(),rev:false,para:false};battle={stage,enemies:enemies.map(x=>({...x,max:x.hp})),idx:0,p,after,boss,guard:boss&&data().treasures[6]===3?2:0,titan:0,titanUsed:false,arcCheck:false,turn:0,log:[]};enc();}
function enc(){if(!battle)return;const b=battle;if(b.idx>=b.enemies.length){const a=b.after;battle=null;if(a)a();return}b.e=b.enemies[b.idx];b.turn=0;b.log.push(`${b.e.name} 등장 · ${b.e.w}`);renderB();}
function log(x){battle?.log.push(x)}
function renderB(){if(!battle)return;const b=battle,p=b.p,e=b.e,t=b.titan>0,tm=arc()?30:15;show(`${top(b.stage)}<div class="f1box ${t?'f1gold':''}"><div class="f1fighters"><div class="f1fighter"><b>주인공 ${t?'⚡':''}</b><div style="font-size:.72rem">${p.weapon.name} · ATK ${p.atk}${t?' ×'+tm:''}</div><div class="f1hp"><div class="f1fill" style="width:${Math.max(0,p.hp/p.max*100)}%"></div></div>${Math.max(0,Math.ceil(p.hp))}/${p.max}</div><div class="f1fighter"><b>${e.name}</b><div style="font-size:.72rem">${e.w} · ATK ${e.atk.toLocaleString()}</div><div class="f1hp"><div class="f1fill e" style="width:${Math.max(0,e.hp/e.max*100)}%"></div></div>${Math.max(0,Math.ceil(e.hp)).toLocaleString()}/${e.max.toLocaleString()}</div></div><div class="f1log">${b.log.slice(-14).map(x=>`<div>${x}</div>`).join('')}</div>${btn(p.para?'마비됨':'공격',attack,p.para?'btn':'btn btn-danger')}${titanOK()&&!b.titanUsed?btn(`⚡ ${arc()?'ARC TITAN ×30':'TITAN ×15'} · 3턴`,useTitan,'btn btn-super'):''}</div>${back()}`);const l=document.querySelector('.f1log');if(l)l.scrollTop=l.scrollHeight;}
function useTitan(){if(!battle||battle.titanUsed)return;battle.titanUsed=true;battle.titan=3;log(arc()?'ARC CORE · OVERLAY MODE ×30':'TITAN CORE · LIMIT RELEASE ×15');renderB();}
function attack(){if(!battle)return;const b=battle,p=b.p,e=b.e;if(p.para){p.para=false;log('⚡ 마비로 행동 불가');return enemyTurn()}let dmg=p.atk*(b.titan>0?(arc()?30:15):1);if(p.weapon.type==='overlay'&&Math.random()<.20){dmg=Math.round(dmg*1.8);log('🌀 중력 붕괴 · 1.8배')}if(e.def)dmg=Math.round(dmg*(1-Math.max(0,e.def-(p.weapon.type==='overlay'?.30:0))));e.hp-=dmg;log(`주인공 ${dmg.toLocaleString()} 피해`);if(p.weapon.type==='overlay'&&e.hp>0&&Math.random()<.10){e.lock=true;log('🔒 GRAVITY LOCK · 적 1턴 봉쇄')}if(e.hp<=0)return down();enemyTurn();}
function enemyTurn(){if(!battle)return;const b=battle,p=b.p,e=b.e;if(e.lock){e.lock=false;log('중력 제압으로 적 행동 불가');return finish()}if(b.guard>0){b.guard--;log('🌊 파도의 수호 · 공격 완전 방어');return finish()}if(Math.random()<.15){log('💨 미래형 전투복 · 회피');return finish()}b.turn++;let raw=e.atk;if(e.heavy&&b.turn%e.heavy===0){raw*=2;log('⚠ 강화 포격')}const dmg=Math.round(raw*.40);p.hp-=dmg;log(`${e.name} ${dmg.toLocaleString()} 피해 (전투복 60% 감소)`);if(e.para&&Math.random()<e.para){p.para=true;log('⚡ 전기 충격 · 마비')}if(b.titan>0&&arc()&&!b.arcCheck&&p.hp/p.max<.15){b.arcCheck=true;log('ARC CORE CRITICAL · HP 15% 미만');if(Math.random()<.50){p.hp=Math.max(1,p.hp);e.hp=0;log('💥 반중력 폭발 · 상대 즉사');renderB();return setTimeout(down,400)}log('반중력 폭발 실패')}if(p.hp<=0){if(data().treasures[5]===3&&!p.rev){p.rev=true;p.hp=Math.max(1,Math.round(p.max*.30));log('✦ 성지순례 · HP 30% 부활')}else{return defeat()}}finish();}
function finish(){if(!battle)return;if(battle.titan>0){battle.titan--;if(!battle.titan)log('TITAN CORE OUTPUT : 0%')}renderB();}
function down(){if(!battle)return;log(`${battle.e.name} 격파`);battle.idx++;setTimeout(enc,300)}
function defeat(){const s=battle.stage;battle=null;show(`${top(s)}<div class="f1box f1bad" style="text-align:center">DEFEAT</div>${btn('다시 도전',()=>openStoryStage('future1',s),'btn btn-danger')}${back()}`)}
function stopQ(){if(qte?.timer)clearInterval(qte.timer);qte=null}
function startQ(){stopQ();qte={r:1,hp:3,ok:0,pos:0,dir:1};qround()}
function qround(){if(!qte)return;if(qte.r>6){const n=qte.ok;stopQ();return clear(2,`네온 고속도로 추격을 돌파한다.\n\n오토바이 무장 슬롯의 <b>레이저 쌍권총</b>을 챙긴다.\n\nQTE 성공 ${n}/6`)}show(`${top(2,'OVERDRIVE CITY')}<div class="f1box"><div>레이저 조준선이 접근한다. 초록 구간에서 회피!</div><div class="f1q"><div class="f1z"></div><div class="f1p"></div><div id="f1cursor" class="f1c"></div></div>${btn('🏍️ 지금 회피!',qhit,'btn btn-super')}<div id="f1qs" style="font-size:.78rem;text-align:center">${qte.r}/6 · 내구도 ${qte.hp}/3</div></div>${back()}`);qte.timer=setInterval(()=>{if(!qte)return;qte.pos+=qte.dir*2.3;if(qte.pos>99){qte.pos=99;qte.dir=-1}if(qte.pos<0){qte.pos=0;qte.dir=1}const c=$('f1cursor');if(c)c.style.left=qte.pos+'%'},24)}
function qhit(){if(!qte)return;if(qte.timer)clearInterval(qte.timer);const p=qte.pos,ok=p>=42&&p<=58,perf=p>=47&&p<=53;if(ok){qte.ok++;$('f1qs').innerHTML=perf?'<span class="f1good">PERFECT · 회피 + 반격</span>':'<span class="f1good">회피 성공</span>'}else{qte.hp--;$('f1qs').innerHTML='<span class="f1bad">피격 · 내구도 -1</span>'}if(qte.hp<=0)return setTimeout(()=>{stopQ();show(`${top(2)}<div class="f1box f1bad" style="text-align:center">CRASH</div>${btn('다시 도전',startQ,'btn btn-danger')}${back()}`)},350);qte.r++;setTimeout(qround,420)}
function s1(){show(`${top(1,'CHRONO PANIC')}<div class="f1s">고대의 가면이 폭주한 뒤 주인공은 약 100년 뒤의 미래도시에서 눈을 뜬다.\n\n거리 단말기의 날짜를 확인하는 순간 보안 시스템이 신원불명자를 감지한다.\n<div class="f1sys">UNKNOWN CITIZEN DETECTED\nIDENTITY : NOT FOUND</div>파손된 긴급 장비함에서 <b>미래형 전투복</b>을 착용한다.\n<div class="f1gold">HP +300 · 받는 피해 60% 감소 · 회피 15%</div></div>${btn('보안 드론 돌파',()=>startBattle(1,E[1],()=>clear(1,'도시 전체에 신원불명 경보가 퍼진다.'),false),'btn btn-danger')}${back()}`)}
function s2(){show(`${top(2,'OVERDRIVE CITY')}<div class="f1s">보안부대가 몰려온다. 주인공은 미래형 오토바이를 탈취한다.\n\n“사용법은…… 대충 알겠군.”\n\n네온 고속도로 위에서 레이저 추격전이 시작된다.</div>${btn('🏍️ 오버드라이브',startQ,'btn btn-super')}${back()}`)}
function s3(){show(`${top(3)}<div class="f1s">미래 기록도시 콘스탄티노폴리스.\n\n<div class="f1sys">KILL OF KING · DISBANDED\nOPERATIVE · MISSING</div>주인공은 자신이 약 100년 전 실종자로 기록돼 있음을 확인한다.\n\n최심부에서 <b>타이탄 코어</b>가 미래형 전투복과 연결된다.\n<div class="f1gold">전투당 1회 · 자신의 턴 3턴 · 공격력 ×15</div></div>${btn('타이탄 코어 장착',()=>clear(3,'타이탄 시스템이 활성화된다.'))}${back()}`)}
function s4(){show(`${top(4)}<div class="f1s">아크 지구 중앙 연구시설. 타이탄 코어가 아크 코어 신호에 반응한다.\n<div class="f1sys">ARC CORE SIGNAL DETECTED\nSECURITY LEVEL : MAXIMUM</div>아크 가디언이 중앙 코어를 지키고 있다.</div>${btn('아크 시설 돌파',()=>startBattle(4,E[4],()=>clear(4,'아크 코어가 타이탄 코어와 동기화된다.<br><br><b>ARC TITAN · 공격력 ×30 · 3턴</b>'),false),'btn btn-danger')}${back()}`)}
function s5(){show(`${top(5)}<div class="f1s">예루살렘의 역사 데이터 보관소. 고대의 가면과 비슷한 문양이 여러 기록에 남아 있지만 핵심 기록은 지워져 있다.\n\n주인공은 고대에서 보았던 사건이 역사에서 의도적으로 사라졌을 가능성을 의심한다. 봉인의 대상은 아직 알 수 없다.</div>${btn('성역 조사 완료',()=>clear(5,'달로 향하기 위한 좌표가 아틀란티스에 보관되어 있음을 확인한다.'))}${back()}`)}
function s6(){show(`${top(6)}<div class="f1s">100년 뒤의 거대 해저도시 아틀란티스. 달 기지 궤도 좌표는 중앙 코어에 봉인되어 있다.\n<div class="f1sys">ATLANTIS SECURITY SYSTEM\nINTRUDER DETECTED</div>아틀란티스 경비병 → 심해 수호기 → 아틀란티스 수호자가 길을 막는다.</div>${btn('중앙 코어 돌파',()=>startBattle(6,E[6],()=>clear(6,'아틀란티스 수호자 격파.<br><br>달 기지 좌표와 <b>오버레이 반중력포</b>를 획득한다.<br>ATK 350 · 중력 붕괴 20% · 중력 제압 10% · 방어효과 30% 무시'),false),'btn btn-danger')}${back()}`)}
function s7(){const s=bossS();show(`${top(7,'NEON SIGNAL')}<div class="f1s">폐허가 된 월면 시간관측소. 중앙 관제실에 한 남자만 남아 있다.\n\n<span class="f1gold">??? : “……돌아가.”</span>\n<div class="f1sys">IDENTIFICATION\n노범수 / 월면 시간관측소 책임자\nNEURAL LIMITER : FAILURE</div><b>폭주한 노범수</b>\n${s.m}배율 · HP ${s.hp.toLocaleString()} · ATK ${s.atk.toLocaleString()}\n\n4-1~4-6 보물만 배율 감소에 적용된다.</div>${btn('폭주한 노범수와 전투',()=>startBattle(7,[{name:'폭주한 노범수',hp:s.hp,atk:s.atk,w:'월면 중력포 · 강화 의수'}],()=>clear(7,'노범수가 쓰러지고 월면 시간관측 장치의 잠금이 해제된다.'),true),'btn btn-danger')}${back()}`)}
function s8(){show(`${top(8)}<div class="f1s">고대의 가면과 월면 시간관측 장치를 연결한다. 원래 시대의 좌표가 고정되지만 아크 코어가 과출력에 들어간다.\n<div class="f1sys">ARC CORE OUTPUT : 121%\nARC CORE OUTPUT : 147%\nCORE STRUCTURE FAILURE\n\nTIME OVER</div>시간 통로가 열리는 순간 아크 코어가 산산이 부서진다.\n\n<b>타이탄 시스템은 이후 사용할 수 없다.</b></div>${btn('시간선을 초월한다',()=>clear(8,'원래 시대의 지구로 귀환한다.<br><br>킬 오브 킹 연구원: “이 기술은 어디서 구한 겁니까?”<br>주인공: “100년 뒤.”<br><br>복구는 불가능하지만 코어 원리를 연구하기 시작한다.<br><b>지구 II로 이어진다.</b>'),'btn btn-super')}${back()}`)}
const oldRC=window.renderStoryChapter;if(typeof oldRC==='function')window.renderStoryChapter=function(id){if(id==='future1')return renderChapter();return oldRC.apply(this,arguments)};
const oldOS=window.openStoryStage;if(typeof oldOS==='function')window.openStoryStage=function(ch,n){if(ch!=='future1')return oldOS.apply(this,arguments);if(!storyStageUnlocked('future1',n)){alert('앞 스테이지를 먼저 클리어하세요.');return}stopQ();battle=null;stopMusic();if(typeof startFutureStageBgm==='function')startFutureStageBgm(+n);[null,s1,s2,s3,s4,s5,s6,s7,s8][+n]?.()};
window.LRFuture1={getBossMultiplier:bossM,getBossStats:bossS,getTreasureAttackBonus:()=>tc()*15};
})();
