/* Lost Ruby - Noh Beom-su boss v7: intro restored / 45% gate / easier parry */
(()=>{
const $=id=>document.getElementById(id),CH='future1',ST=7,GN=['없음','낡은','평범','최고급'];
let R=null,seq=0;
function D(root=saveData){root.story??={};root.story.stages??={};root.story.clearedChapters??={};root.story.future1Data??={};const d=root.story.future1Data;d.treasures??={};d.lpRewarded??={};for(let i=1;i<=8;i++)d.treasures[i]=Math.max(0,Math.min(3,+d.treasures[i]||0));return d}
const T=()=>D().treasures,alive=(r=R)=>!!r&&!r.done&&R===r;
function timers(r=R){if(!r)return;(r.to||[]).forEach(clearTimeout);(r.iv||[]).forEach(clearInterval);r.to=[];r.iv=[]}
function later(fn,ms,r=R){const x=setTimeout(()=>{if(alive(r))fn()},ms);r?.to?.push(x);return x}
function stop(){if(R){R.done=true;timers(R);R=null}try{stopFutureStageBgm?.()}catch(_){}}
function css(){if($('n7css'))return;const s=document.createElement('style');s.id='n7css';s.textContent=`#future1-stage-screen{padding:18px}.n7s{background:linear-gradient(180deg,#12213b,#0c1224);border-left:3px solid #69b8ff;border-radius:14px;padding:16px;margin:10px 0;line-height:1.8}.n7sys{font-family:monospace;color:#a8ddff;background:#080d18;border:1px solid #29466d;border-radius:10px;padding:10px;margin:9px 0;white-space:pre-line}.n7b{background:linear-gradient(180deg,#101827,#090e18);border:1px solid #314766;border-radius:14px;padding:13px;margin:9px 0}.n7ph{text-align:center;border:1px solid #4c6790;border-radius:11px;padding:9px;color:#a9d7ff;font-weight:900;background:#0c1422}.n7f{display:flex;gap:8px}.n7u{flex:1;min-width:0;text-align:center;background:#070b12;border:1px solid #2c3d57;border-radius:10px;padding:9px}.n7hp{height:13px;background:#303746;border-radius:8px;overflow:hidden;margin:6px 0}.n7fill{height:100%;background:#48ca83}.n7fill.e{background:#df4f62}.n7log{height:150px;overflow:auto;background:#05080d;border-radius:10px;padding:9px;font-size:.77rem;line-height:1.5;margin:9px 0}.g{color:#78ffad;font-weight:900}.r{color:#ff8797;font-weight:900}.y{color:#ffe26f;font-weight:900}.c{color:#a9d7ff;font-family:monospace}.lanes{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.lane{min-height:62px;background:#2b3448}.lane.hint{background:#16573c!important;box-shadow:0 0 18px rgba(90,255,170,.55);outline:2px solid #62ffb3}.track{height:78px;background:#05080d;border:1px solid #293a55;border-radius:10px;position:relative;overflow:hidden}.safe{position:absolute;left:40%;width:20%;height:100%;background:rgba(58,186,116,.28)}.perf{position:absolute;left:47%;width:6%;height:100%;background:rgba(235,198,60,.38)}.cur{position:absolute;width:6px;height:100%;background:#ff5a72;box-shadow:0 0 12px #ff5a72}.par{height:126px;background:#05080d;border:1px solid #293a55;border-radius:12px;position:relative;overflow:hidden}.core,.target,.ring{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);border-radius:50%}.core{width:52px;height:52px;border:3px solid #76c9ff;box-shadow:0 0 17px #3c9ddc;display:flex;align-items:center;justify-content:center;font-size:.67rem;color:#bde8ff}.target{width:82px;height:82px;border:4px solid #5cffad;box-shadow:0 0 17px rgba(92,255,173,.62)}.ring{width:190px;height:190px;border:4px solid #ff596d}.hint{text-align:center;font-size:.75rem;opacity:.78;margin:7px 0}`;document.head.appendChild(s)}
function scr(){css();let e=$('future1-stage-screen');if(!e){e=document.createElement('div');e.id='future1-stage-screen';e.className='screen';$('app')?.appendChild(e)}return e}
function show(h){scr().innerHTML=h;showScreen('future1-stage-screen')}
const top=(x='')=>`<h2 style="text-align:center">🌆 4-7 · 달</h2><p style="text-align:center;opacity:.7;font-size:.8rem">${x}</p>`;
function B(t,f,cl='btn btn-gold'){const id='n7'+Math.random().toString(36).slice(2);setTimeout(()=>{$(id)&&($(id).onclick=f)},0);return`<button id="${id}" class="${cl}">${t}</button>`}
function log(t,k=''){R?.log.push({t,k});if(R?.log.length>40)R.log.shift()}
function fight(){const p=R.p,e=R.e;return`<div class="n7f"><div class="n7u"><b>주인공</b><div style="font-size:.7rem">${p.w} · ATK ${p.atk.toLocaleString()}</div><div class="n7hp"><div class="n7fill" style="width:${Math.max(0,p.hp/p.max*100)}%"></div></div>${Math.max(0,Math.ceil(p.hp))}/${p.max}</div><div class="n7u"><b>폭주한 노범수</b><div style="font-size:.7rem">월면 중력포 · 강화 의수 · ATK ${e.atk.toLocaleString()}</div><div class="n7hp"><div class="n7fill e" style="width:${Math.max(0,e.hp/e.max*100)}%"></div></div>${Math.max(0,Math.ceil(e.hp)).toLocaleString()}/${e.max.toLocaleString()}</div></div>`}
function shell(ph,body){show(`${top('NEON SIGNAL')}<div class="n7ph">${ph}</div><div class="n7b">${fight()}<div class="n7log">${R.log.slice(-12).map(x=>`<div class="${x.k}">${x.t}</div>`).join('')}</div>${body}</div>${B('← 스테이지 목록',()=>{stop();openStoryChapter(CH)},'btn')}`)}
function lose(x){if(!R||R.done)return;R.done=true;timers(R);show(`${top()}<div class="n7b r" style="text-align:center;font-size:1.15rem">DEFEAT<div style="font-size:.78rem;margin-top:7px">${x}</div></div>${B('다시 도전',()=>openStoryStage(CH,ST),'btn btn-danger')}${B('← 스테이지 목록',()=>openStoryChapter(CH),'btn')}`);R=null}
function hit(mult=1){if(R.guard){R.guard--;log(`🌊 심해 결정체 · 공격 완전 방어 (${R.guard}회 남음)`,'g');return false}if(Math.random()<.15){log('💨 미래형 전투복 · 공격 회피','g');return false}const dm=Math.round(R.e.atk*.4*mult);R.p.hp-=dm;log(`노범수 공격 · ${dm.toLocaleString()} 피해`,'r');if(R.p.hp<=0){if(T()[5]===3&&!R.p.rev){R.p.rev=true;R.p.hp=Math.max(1,Math.round(R.p.max*.3));log('✦ 성지순례 · HP 30% 부활','y');return false}lose('노범수의 공격에 쓰러졌다.');return true}return false}
function counter(perfect){let dm=Math.round(R.p.atk*30*(perfect?1.2:1));if(Math.random()<.2){dm=Math.round(dm*1.8);log('🌀 중력 붕괴 · 1.8배','y')}R.e.hp-=dm;log(`⚡ ARC TITAN 반격 · ${dm.toLocaleString()} 피해`,perfect?'y':'g');if(R.e.hp<=0){R.e.hp=0;later(()=>win('ARC TITAN'),250);return true}return false}
function p1(){if(!alive())return;R.phase=1;R.round++;if(R.round>3){log('[ARC SYNC : 100%]','c');log('⚡ ARC TITAN 동기화 완료','y');R.round=0;return later(p2,600)}const names=['LUNAR-A','LUNAR-B','LUNAR-C'],safe=Math.random()*3|0;let picked=false,on=false;shell(`PHASE 1 · GRAVITY FIELD ${R.round}/3`,`<div style="text-align:center;margin-bottom:8px">안전 구역이 잠깐 초록색으로 점멸한다.</div><div class="lanes">${names.map((n,i)=>`<button id="ln${i}" class="btn lane" disabled>${n}</button>`).join('')}</div><div id="lm" class="hint">SCAN...</div>`);names.forEach((_,i)=>{$('ln'+i).onclick=()=>{if(!alive()||picked||!on)return;picked=true;timers();if(i===safe)log(`${names[i]} 진입 · 회피 성공`,'g');else{log(`잘못된 구역 · 안전구역 ${names[safe]}`,'r');if(hit())return}later(p1,380)}});later(()=>{$('ln'+safe)?.classList.add('hint');if($('lm'))$('lm').textContent='SAFE SIGNAL DETECTED'},300);later(()=>{names.forEach((_,i)=>{const b=$('ln'+i);if(b){b.classList.remove('hint');b.disabled=false}});on=true;if($('lm'))$('lm').textContent='지금 선택'},760);later(()=>{if(picked)return;picked=true;log('안전구역 선택 시간 초과','r');if(!hit())later(p1,380)},2800)}
const A=[['GRAVITY SPEAR',2.8,1],['LUNAR RUSH',3.5,1.05],['ARM BREAKER',4.1,1.15]];
function p2(){if(!alive())return;R.phase=2;R.round++;if(R.round>3){log('[ARC TITAN OUTPUT : END]','c');if(R.e.hp/R.e.max>.45)return lose('ARC TITAN 종료 시 노범수 체력이 45%를 초과했다.');R.round=0;log('노범수의 최후 공격이 시작된다.','y');return later(p3,650)}const [name,spd,mul]=A[R.round-1];let pos=0,dir=1,lock=false;shell(`PHASE 2 · DIRECT ASSAULT ${R.round}/3`,`<div style="text-align:center"><b>${name}</b><br><span style="font-size:.75rem">빨간 표식이 초록 범위에 들어올 때 회피</span></div><div class="track"><div class="safe"></div><div class="perf"></div><div id="cur" class="cur"></div></div><button id="dodge" class="btn btn-super">💨 회피</button><div class="hint">초록=성공 · 노랑=PERFECT · 좌↔우 왕복</div>`);$('dodge').onclick=()=>{if(lock||!alive())return;lock=true;timers();const ok=pos>=40&&pos<=60,pf=pos>=47&&pos<=53;if(ok){log(`${name} · ${pf?'PERFECT DODGE':'회피 성공'}`,pf?'y':'g');if(counter(pf))return}else{log(`${name} · 회피 실패`,'r');if(hit(mul))return}later(p2,430)};const iv=setInterval(()=>{if(lock||!alive())return;pos+=dir*spd;if(pos>=99){pos=99;dir=-1}if(pos<=0){pos=0;dir=1}if($('cur'))$('cur').style.left=pos+'%'},20);R.iv.push(iv);later(()=>{if(lock)return;lock=true;timers();log(`${name} · 회피 타이밍 놓침`,'r');if(!hit(mul))later(p2,430)},3200)}
function p3(){if(!alive())return;R.phase=3;R.round++;if(R.round>3)return win('FINAL STRIKE 3회 전부 튕겨내기');let size=190,lock=false;shell(`PHASE 3 · FINAL PARRY ${R.round}/3`,`<div style="text-align:center">빨간 충격파가 <b style="color:#5cffad">초록 링</b>과 겹칠 때 튕겨내기</div><div class="par"><div class="target"></div><div class="core">ARC</div><div id="ring" class="ring"></div></div><button id="parry" class="btn btn-success">🛡️ 튕겨내기</button><div class="hint">성공 판정 확대 · 충격파 속도 완화</div>`);$('parry').onclick=()=>{if(lock||!alive())return;lock=true;timers();const pf=size>=58&&size<=76,ok=size>=48&&size<=92;if(!ok)return lose('최후의 공격을 튕겨내지 못했다.');log(`FINAL STRIKE ${R.round} · ${pf?'PERFECT PARRY':'PARRY 성공'}`,pf?'y':'g');if(pf){const dm=Math.round(R.p.atk*30*.3);R.e.hp=Math.max(1,R.e.hp-dm);log(`PERFECT 반격 · ${dm.toLocaleString()} 피해`,'g')}later(p3,430)};const iv=setInterval(()=>{if(lock||!alive())return;size-=2.85+R.round*.2;const x=$('ring');if(x){x.style.width=size+'px';x.style.height=size+'px'}if(size<=42){lock=true;timers();lose('최후의 공격을 튕겨내지 못했다.')}},22);R.iv.push(iv)}
function roll(){const d=D(),old=d.treasures[7]||0,x=Math.random(),g=x<.1?3:x<.3?2:x<.65?1:0;let first=false;if(g>old){d.treasures[7]=g;first=old===0}return{g,cur:d.treasures[7],first}}
const cloud=()=>typeof useCloud!=='undefined'&&useCloud&&fbDb&&fbUserId;
async function lp50(){const d=D();if(d.lpRewarded[7])return 0;if(!cloud()){d.lpRewarded[7]=true;saveData.lp=(+saveData.lp||0)+50;return 50}let out=null;const ref=fbDb.collection('profiles').doc(fbUserId);await fbDb.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw Error('PROFILE_NOT_FOUND');const p=s.data()||{},base=Object.assign(defaultSaveData(p.nick||saveData.nick||''),p.data||{}),fd=D(base),now=D();base.story.stages.future1=Math.max(+base.story.stages.future1||0,7);for(let i=1;i<=8;i++)fd.treasures[i]=Math.max(+fd.treasures[i]||0,+now.treasures[i]||0);let lp=Math.max(0,+(p.lp!==undefined?p.lp:base.lp)||0),ok=false;if(!fd.lpRewarded[7]){fd.lpRewarded[7]=true;lp+=50;ok=true}base.lp=lp;base.lr=Math.max(0,+(p.lr!==undefined?p.lr:base.lr)||0);tx.set(ref,{nick:base.nick||p.nick||'',lr:base.lr,lp,data:base,updated_at:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});out={base,ok}});if(out)saveData=Object.assign(defaultSaveData(out.base.nick||saveData.nick||''),out.base);return out?.ok?50:0}
async function win(reason){if(!R||R.fin)return;R.fin=true;R.done=true;timers();saveData.story.stages.future1=Math.max(+saveData.story.stages.future1||0,7);const dr=roll();let gain=0,err=false;if(dr.cur===3&&!D().lpRewarded[7])try{gain=await lp50()}catch(e){console.warn(e);err=true}try{persistSave()}catch(_){}let z=dr.g?`${GN[dr.g]} 월석 파편 등장`:'보물 없음';if(dr.first)z+='<br><span class="g">최초 획득 · 미래편 공격력 +15%</span>';if(gain)z+=`<br><b>LP +${gain}</b>`;if(err)z+='<br><span class="r">LP 지급 실패 · 다음 클리어 때 재시도</span>';show(`${top()}<div class="n7b"><div class="y">폭주한 노범수를 격파했다.</div><div>${reason}</div><div class="g" style="text-align:center;font-size:1.2rem">STAGE CLEAR</div></div><div class="n7b y" style="text-align:center">💎 ${z}</div>${B('다음 · 4-8 타임오버',()=>openStoryStage(CH,8),'btn btn-success')}${B('← 스테이지 목록',()=>openStoryChapter(CH),'btn')}`);R=null}
function battle(){const s=LRFuture1?.getBossStats?.(),p=LRFuture1?.getPlayerStats?.(7);if(!s||!p)return alert('미래편 전투 데이터를 불러오지 못했습니다.');R={id:++seq,done:false,fin:false,phase:1,round:0,to:[],iv:[],guard:T()[6]===3?2:0,log:[],p:{max:+p.maxHp||800,hp:+p.maxHp||800,atk:+p.attack||350,w:p.weapon?.name||'오버레이 반중력포',rev:false},e:{max:+s.hp,hp:+s.hp,atk:+s.atk,m:+s.m}};log(`[BOSS MULTIPLIER : ×${R.e.m}]`,'c');log('노범수 : “……돌아가.”');log('NEURAL LIMITER : FAILURE','r');shell('BOSS READY',`<div style="text-align:center"><b>폭주한 노범수</b><br>HP ${R.e.max.toLocaleString()} · ATK ${R.e.atk.toLocaleString()}</div>${B('⚡ 전투 시작',()=>{R.round=0;p1()},'btn btn-danger')}`)}
function intro(){stop();const s=LRFuture1?.getBossStats?.();if(!s)return alert('미래편 보스 데이터를 불러오지 못했습니다.');try{startFutureStageBgm?.(7)}catch(_){}show(`${top('NEON SIGNAL')}<div class="n7s">폐허가 된 <b>월면 시간관측소</b>.<br><br>주인공이 중앙 관제실에 들어서자, 꺼진 관측 장치 사이에 한 남자만 홀로 서 있다.<br><br><span class="y">??? : “……돌아가.”</span><div class="n7sys">IDENTIFICATION
노범수 / 월면 시간관측소 책임자
NEURAL LIMITER : FAILURE</div>신경 제한기가 완전히 망가진 노범수의 강화 의수와 월면 중력포가 동시에 기동한다.<br><br><b>폭주한 노범수</b><br>배율 ×${s.m} · HP ${s.hp.toLocaleString()} · ATK ${s.atk.toLocaleString()}<br><span style="font-size:.75rem;opacity:.72">4-1~4-6 보물 등급이 노범수 배율에 적용된다.</span></div>${B('폭주한 노범수와 전투',battle,'btn btn-danger')}${B('← 스테이지 목록',()=>{stop();openStoryChapter(CH)},'btn')}`)}
const old=window.openStoryStage;window.openStoryStage=function(ch,n){if(ch!==CH||+n!==ST)return old?.apply(this,arguments);if(typeof storyStageUnlocked==='function'&&!storyStageUnlocked(CH,ST))return alert('앞 스테이지를 먼저 클리어하세요.');intro()};window.LRNohBossV7={start:intro,stop};
})();
